# Generated by Django 5.2.14 on 2026-06-02 13:44

import devices.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_iotnode_interactive_simulation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iotnode',
            name='last_payload',
            field=models.JSONField(blank=True, default=devices.models._default_last_payload),
        ),
        migrations.AlterField(
            model_name='iotnode',
            name='lat',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)]),
        ),
        migrations.AlterField(
            model_name='iotnode',
            name='lng',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)]),
        ),
        migrations.AlterField(
            model_name='iotnode',
            name='runtime_state',
            field=models.JSONField(blank=True, default=devices.models._default_runtime_state),
        ),
    ]
