# Generated by Django 5.2.14 on 2026-06-02 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='telemetry',
            new_name='telemetry_t_node_id_d39d1f_idx',
            old_name='telemetry_t_node_id_00eef6_idx',
        ),
        migrations.RenameIndex(
            model_name='telemetry',
            new_name='telemetry_t_status_36a78d_idx',
            old_name='telemetry_t_status_4e68de_idx',
        ),
    ]
